name: Pylint

on: 
  pull_request:
    branches:
      - main  # Cambia según rama principal
    paths:  
      - '**.py' # Se dispara sólo con esos ficheros

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout Code
      uses: actions/checkout@v4
    # Paso 2: Configurar Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    # Paso 3: Instalar dependencias        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    # Paso 4: Ejecutar pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
